site_name: ISPP 18
pages:
- Inicio: 'index.md'
- Trabajo: 'trabajo.md'
- Metodología: 'metodologia.md'
- Organización: 'organizacion.md'
- Otros: 'otros.md'
- Feedback: 'feedbacks.md'
theme:
    name: 'material'
markdown_extensions:
- toc:
    permalink: True
