site_name: ISPP 18
pages:
- Inicio: 'index.md'
- Asignatura:
  - General: 'asignatura.md'
- Grupo: 
  - Documentación:
    - General: 'documentacion.md'
    - Actas de reunión: 'actas de reunión.md'
    - Plantillas: 'plantillas.md'
  - Producto:
    - General: 'producto.md'
    - Web: 
      - Guia de estilo: "guia de estilo.md"
      - Manual de uso de plantilla: 'manual de uso.md'
  - Metodología:
    - Inicial: 'metodologia.md'
    - Esquema de trabajo para API: 'esquema_trabajo_api.md'
  - Organización: 'organizacion.md'
  - Gestión de Ramas: 'gestion_ramas.md'
- Feedbacks:
  - Clase 02/03/2018:
    - Mañana:
      - 02-M01 feedback: "feedbacks/02/02-M01 feedback.md"
      - 02-M02 feedback: "feedbacks/02/02-M02 feedback.md"
      - 02-M03 feedback: "feedbacks/02/02-M03 feedback.md"
      - 02-M04 feedback: "feedbacks/02/02-M04 feedback.md"
    - Tarde:
      - 02-T01 feedback: "feedbacks/02/02-T01 feedback.md"
      - 02-T02 feedback: "feedbacks/02/02-T02 feedback.md"
      - 02-T03 feedback: "feedbacks/02/02-T03 feedback.md"
      - 02-T04 feedback: "feedbacks/02/02-T04 feedback.md"
      - 02-T05 feedback: "feedbacks/02/02-T05 feedback.md"
      - 02-T06 feedback: "feedbacks/02/02-T06 feedback.md"
      - 02-T07 feedback: "feedbacks/02/02-T07 feedback.md"
      - 02-T08 feedback: "feedbacks/02/02-T08 feedback.md"
      - 02-T general: "feedbacks/02/02-T0X general.md"
  - Clase 09/03/2018:
    - Mañana:
      - 03-M01 Art-in-bar: "feedbacks/03/03-M01 Art-in-bar.md"
      - 03-M02 PetMyPet: "feedbacks/03/03-M02 PetMyPet.md"
      - 03-M03 Homely: "feedbacks/03/03-M03 Homely.md"
      - 03-M04 OldKare: "feedbacks/03/03-M04 OldKare.md"
    - Tarde:
      - 03-T01 Cocome: "feedbacks/03/03-T01 Cocome.md"
      - 03-T02 Traveliers: "feedbacks/03/03-T02 Traveliers.md"
      - 03-T03 Makai: "feedbacks/03/03-T03 Makai.md"
      - 03-T04 Climbcode: "feedbacks/03/03-T04 Climbcode.md"
      - 03-T05 Drafter: "feedbacks/03/03-T05 Drafter.md"
      - 03-T06 QRico: "feedbacks/03/03-T06 QRico.md"
      - 03-T07 Adrenalive: "feedbacks/03/03-T07 Adrenalive.md"
      - 03-T08 QuickAcademy: "feedbacks/03/03-T08 QuickAcademy.md"
  - Clase 16/03/2018:
    - Mañana:
      - 04-M01 PetMyPet: "feedbacks/04/04-M01 PetMyPet.md"
      - 04-M02 Homely: "feedbacks/04/04-M02 Homely.md"
      - 04-M03 OldKare: "feedbacks/04/04-M03 OldKare.md"
      - 04-M04 Vapours: "feedbacks/04/04-M04 Vapours.md"
    - Tarde:
      - 04-T01 QuickAdemy: "feedbacks/04/04-T01 QuickAcademy.md"
      - 04-T02 QRico: "feedbacks/04/04-T02 QRico.md"
      - 04-T03 Drafter: "feedbacks/04/04-T03 Drafter.md"
      - 04-T04 Adrenalive: "feedbacks/04/04-T04 Adrenalive.md"
      - 04-T05 Travelliers: "feedbacks/04/04-T05 Travelliers.md"
      - 04-T06 Climbcode: "feedbacks/04/04-T06 Climbcode.md"
      - 04-T07 Cocome: "feedbacks/04/04-T07 Cocome.md"
      - 04-T08 Makai: "feedbacks/04/04-T08 Makai.md"
      - 04-TXX Conclusiones: "feedbacks/04/04-TXX Conclusiones.md"
  - Clase 23/03/2018:
    - Tarde:
      - 05-T01 Climbcode: "feedbacks/05/05-T01 Climbcode.md"
      - 05-T02 Cocome: "feedbacks/05/05-T02 Cocome.md"
      - 05-T03 Traveliers: "feedbacks/05/05-T03 Traveliers.md"
      - 05-T04 Makai: "feedbacks/05/05-T04 Makai.md"
      - 05-T05 Drafter: "feedbacks/05/05-T05 Drafter.md"
      - 05-T06 Quickademy: "feedbacks/05/05-T06 Quickademy.md"
      - 05-T07 QRico: "feedbacks/05/05-T07 QRico.md"
      - 05-T08 Adrenalive: "feedbacks/05/05-T08 Adrenalive.md"
      - 05-TXX Conclusiones: "feedbacks/05/05-TXX Conclusiones.md"
  - Clase 06/04/2018:
    - Tarde:
      - 06-T01 Drafter.md: "feedbacks/06/06-T01 Drafter.md"
      - 06-T02 Adrenalive.md: "feedbacks/06/06-T02 Adrenalive.md"
      - 06-T03 QRico.md: "feedbacks/06/06-T03 QRico.md"
      - 06-T04 QuickAdemy.md: "feedbacks/06/06-T04 QuickAdemy.md"
      - 06-T05 Makai.md: "feedbacks/06/06-T05 Makai.md"
      - 06-T06 Climbcode.md: "feedbacks/06/06-T06 Climbcode.md"
      - 06-T07 Cocome.md: "feedbacks/06/06-T07 Cocome.md"
      - 06-TXX Conclusiones.md: "feedbacks/06/06-TXX Conclusiones.md"
  - Clase 13/04/2018:
    - Tarde:
      - 07-T01 Climbcode.md: "feedbacks/07/07-T01 Climbcode.md"
      - 07-T02 Cocome.md: "feedbacks/07/07-T02 Cocome.md"
      - 07-T03 Makai.md: "feedbacks/07/07-T03 Makai.md"
      - 07-T04 Adrenalive.md: "feedbacks/07/07-T04 Adrenalive.md"
      - 07-T05 Drafter.md: "feedbacks/07/07-T05 Drafter.md"
      - 07-T06 Quickademy.md: "feedbacks/07/07-T06 Quickademy.md"
      - 07-T07 QRico.md: "feedbacks/07/07-T07 QRico.md"
      - 07-TXX Conclusiones.md: "feedbacks/07/07-TXX Conclusiones.md"
  - Clase 27/04/2018:
    - Tarde: 
      - 08-T01 QuickAdemy.md: "feedbacks/08/08-T01 QuickAdemy.md"
      - 08-T02 Adrenalive.md: "feedbacks/08/08-T02 Adrenalive.md"
      - 08-T03 QRico.md: "feedbacks/08/08-T03 QRico.md"
      - 08-T04 Drafter.md: "feedbacks/08/08-T04 Drafter.md"
      - 08-T05 Makai.md: "feedbacks/08/08-T05 Makai.md"
      - 08-T06 Cocome.md: "feedbacks/08/08-T06 Cocome.md"
      - 08-T07 Climbcode.md: "feedbacks/08/08-T07 Climbcode.md"
      - 08-TXX Conclusiones.md: "feedbacks/08/08-TXX Conclusiones.md"
  - Clase 04/05/2018:
    - Tarde:
      - 09-T01 QRico: "feedbacks/09/09-T01 QRico.md"
      - 09-T02 Cocome: "feedbacks/09/09-T02 Cocome.md"
      - 09-T03 Makai: "feedbacks/09/09-T03 Makai.md"
      - 09-T04 Drafter: "feedbacks/09/09-T04 Drafter.md"
      - 09-T05 Climbcode: "feedbacks/09/09-T05 Climbcode.md"
      - 09-T06 Adrenalive: "feedbacks/09/09-T06 Adrenalive.md"
      - 09-T07 QuickAdemy: "feedbacks/09/09-T07 QuickAdemy.md"
      - 09-TXX Conclusiones: "feedbacks/09/09-TXX Conclusiones.md"
  - Clase 11/05/2018:
    - Tarde:
      - 10-T01 QRico: "feedbacks/10/10-T01 QRico.md"
      - 10-T02 Adrenalive: "feedbacks/10/10-T02 Adrenalive.md"
      - 10-T03 Drafter: "feedbacks/10/10-T03 Drafter.md"
      - 10-T04 Cocome: "feedbacks/10/10-T04 Cocome.md"
      - 10-T05 Makai: "feedbacks/10/10-T05 Makai.md"
      - 10-T06 Climbcode: "feedbacks/10/10-T06 Climbcode.md"
      - 10-T07 Planning: "feedbacks/10/10-T07 Planning.md"
      - 10-TXX Conclusiones: "feedbacks/10/10-TXX Conclusiones.md"
  - Clase 18/05/2018:
    - Tarde:
      - 11-T01 Makai: "feedbacks/11/11-T01 Makai.md"
      - 11-T02 Cocome: "feedbacks/11/11-T02 Cocome.md"
      - 11-T03 InteraTech: "feedbacks/11/11-T03 InteraTech.md"
      - 11-T04 Adrenalive: "feedbacks/11/11-T04 Adrenalive.md"
      - 11-T05 QRico: "feedbacks/11/11-T05 QRico.md"
      - 11-T06 Drafter: "feedbacks/11/11-T06 Drafter.md"
      - 11-T07 Planning: "feedbacks/11/11-T07 Planning.md"
      - 11-TXX Conclusiones: "feedbacks/11/11-TXX Conclusiones.md"
  - Clase 25/05/2018:
    - Tarde:
      - 12-T01 Drafter: "feedbacks/12/12-T01 Drafter.md"
      - 12-T02 Adrenalive: "feedbacks/12/12-T02 Adrenalive.md"
      - 12-T03 QRico: "feedbacks/12/12-T03 QRico.md"
      - 12-T04 InteracTech: "feedbacks/12/12-T04 InteracTech.md"
      - 12-T05 Makai: "feedbacks/12/12-T05 Makai.md"
      - 12-T06 Cocome: "feedbacks/12/12-T06 Cocome.md"
      - 12-T07 StartUs: "feedbacks/12/12-T07 StartUs.md"
      - 12-T08 Conclusiones: "feedbacks/12/12-T08 Conclusiones.md"
  - Clase 01/06/2018:
    - Mañana:
      - 13-MXX Conclusiones: "feedbacks/13/13-MXX Conclusiones.md"
    - Tarde:
      - 13-T01 Presentación: "feedbacks/13/Tarde/13-T01 Presentación.md"
      - 13-T02 QRico: "feedbacks/13/Tarde/13-T02 QRico.md"
      - 13-T03 Cocome: "feedbacks/13/Tarde/13-T03 Cocome.md"
      - 13-T04 Makai: "feedbacks/13/Tarde/13-T04 Makai.md"
      - 13-T05 InteracTeach: "feedbacks/13/Tarde/13-T05 InteracTeach.md"
      - 13-T06 Adrenalive: "feedbacks/13/Tarde/13-T06 Adrenalive.md"
      - 13-T07 Drafter: "feedbacks/13/Tarde/13-T07 Drafter.md"
      - 13-T08 Conclusiones: "feedbacks/13/Tarde/13-T08 Conclusiones.md"
  - Resolución del feedback:
    - Resolución de feedbacks, 1a Entrega: "resolucion_feedbacks.md"    
- Otros: 'otros.md'
- Subir wiki: 'tutorial_subida.md'
theme:
    name: 'material'
markdown_extensions:
- toc:
    permalink: True
