site_name: ISPP 18
pages:
- Inicio: 'index.md'
- Asignatura: 'asignatura.md'
- Documentación: 'documentacion.md'
- Producto: 'producto.md'
- Metodología: 'metodologia.md'
- Organización: 'organizacion.md'
- Otros: 'otros.md'
- Resolución de feedbacks: 'resolucion_feedbacks.md'
- Plantillas: 'plantillas.md'
theme:
    name: 'material'
markdown_extensions:
- toc:
    permalink: True
