site_name: ISPP 18
pages:
- Inicio: 'index.md'
- Trabajo: 'trabajo.md'
- Metodología: 'metodologia.md'
- Organización: 'organizacion.md'
- Otros: 'otros.md'
- Feedback: 'feedbacks.md' 
- Feedback (Presentación): 'feedbacks/presentacion.md'
- Feedback (Contenido): 'feedbacks/contenido.md'
- Feedback (Negocio): 'feedbacks/negocio.md'
- Feedback (Estilo): 'feedbacks/estilo.md'
- Feedback (Adrenalive): 'feedbacks/adrenalive.md'
theme:
    name: 'material'
markdown_extensions:
- toc:
    permalink: True
