site_name: ISPP 18
pages:
- Inicio: 'index.md'
- Asignatura:
  - General: 'asignatura.md'
- Grupo: 
  - Documentación:
    - General: 'documentacion.md'
    - Actas de reunión: 'actas de reunión.md'
    - Plantillas: 'plantillas.md'
  - Producto:
    - General: 'producto.md'
    - Web: 
      - Manual de uso de plantilla: 'manual de uso.md'
  - Metodología: 'metodologia.md'
  - Organización: 'organizacion.md'
  - Gestión de Ramas: 'gestion_ramas.md'
- Feedbacks:
  - Clase 02/03/2018:
    - Mañana:
      - 02-M01 feedback: "feedbacks/02/02-M01 feedback.md"
      - 02-M02 feedback: "feedbacks/02/02-M02 feedback.md"
      - 02-M03 feedback: "feedbacks/02/02-M03 feedback.md"
      - 02-M04 feedback: "feedbacks/02/02-M04 feedback.md"
    - Tarde:
      - 02-T01 feedback: "feedbacks/02/02-T01 feedback.md"
      - 02-T02 feedback: "feedbacks/02/02-T02 feedback.md"
      - 02-T03 feedback: "feedbacks/02/02-T03 feedback.md"
      - 02-T04 feedback: "feedbacks/02/02-T04 feedback.md"
      - 02-T05 feedback: "feedbacks/02/02-T05 feedback.md"
      - 02-T06 feedback: "feedbacks/02/02-T06 feedback.md"
      - 02-T07 feedback: "feedbacks/02/02-T07 feedback.md"
      - 02-T08 feedback: "feedbacks/02/02-T08 feedback.md"
      - 02-T general: "feedbacks/02/02-T0X general.md"
  - Clase 09/03/2018:
    - Mañana:
      - 03-M01 Art-in-bar: "feedbacks/03/03-M01 Art-in-bar.md"
      - 03-M02 PetMyPet: "feedbacks/03/03-M02 PetMyPet.md"
      - 03-M03 Homely: "feedbacks/03/03-M03 Homely.md"
      - 03-M04 OldKare: "feedbacks/03/03-M04 OldKare.md"
    - Tarde:
      - 03-T01 Cocome: "feedbacks/03/03-T01 Cocome.md"
      - 03-T02 Traveliers: "feedbacks/03/03-T02 Traveliers.md"
      - 03-T03 Makai: "feedbacks/03/03-T03 Makai.md"
      - 03-T04 Climbcode: "feedbacks/03/03-T04 Climbcode.md"
      - 03-T05 Drafter: "feedbacks/03/03-T05 Drafter.md"
      - 03-T06 QRico: "feedbacks/03/03-T06 QRico.md"
      - 03-T07 Adrenalive: "feedbacks/03/03-T07 Adrenalive.md"
      - 03-T08 QuickAcademy: "feedbacks/03/03-T08 QuickAcademy.md"
  - Clase 16/03/2018:
    - Mañana:
      - 04-M01 PetMyPet: "feedbacks/04/04-M01 PetMyPet.md"
      - 04-M02 Homely: "feedbacks/04/04-M02 Homely.md"
      - 04-M03 OldKare: "feedbacks/04/04-M03 OldKare.md"
      - 04-M04 Vapours: "feedbacks/04/04-M04 Vapours.md"
    - Tarde:
      - 04-T01 QuickAdemy: "feedbacks/04/04-T01 QuickAcademy.md"
      - 04-T02 QRico: "feedbacks/04/04-T02 QRico.md"
      - 04-T03 Drafter: "feedbacks/04/04-T03 Drafter.md"
      - 04-T04 Adrenalive: "feedbacks/04/04-T04 Adrenalive.md"
      - 04-T05 Travelliers: "feedbacks/04/04-T05 Travelliers.md"
      - 04-T06 Climbcode: "feedbacks/04/04-T06 Climbcode.md"
      - 04-T07 Cocome: "feedbacks/04/04-T07 Cocome.md"
      - 04-T08 Makai: "feedbacks/04/04-T08 Makai.md"
      - 04-TXX Conclusiones: "feedbacks/04/04-TXX Conclusiones.md"
  - Resolución del feedback:
    - Resolución de feedbacks, 1a Entrega: "resolucion_feedbacks.md"    
- Otros: 'otros.md'
- Subir wiki: 'tutorial_subida.md'
theme:
    name: 'material'
markdown_extensions:
- toc:
    permalink: True
